stages:
  - build
  - deploy

job_build:
  stage: build
  script:
    - mvn package docker:build -Dmaven.test.skip=true
  only:
    - master
  tags:
    - crm-build
    
job_deploy:
  stage: deploy
  script:
    - docker stop hycrm && docker rm hycrm
    - docker run -d -p 8010:8010 --name hycrm hy/crm
  only:
    - master
  tags:
    - crm-deploy