# spring boot
server:
  # 服务端口
  port: 8010
  
# spring
spring:
  resources:
    # 默认 classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
    static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:    url: jdbc:mysql://192.168.1.164:10100/crm-dev?characterEncoding=utf-8
    username: root
    password: kKpt3SjkQlT6g79wKSFFVI9y4leZHLAzhahzNuwvVRUQN/ljiPwIjyTlaGMujHtEqCBA45YAH/hnuj9wS2TDoA==
    driver-class-name: com.mysql.jdbc.Driver

#配置模板想到classpath路径，后面须加上"/"
beetl:
  # 启用Beetl
  enabled: true
  # .html模板路径
  templatesPath: templates/
  # 支持后缀为.html的模板
  suffix: html
  # 自动检查模板变化
  beetlsq:
    # 上线要关闭
    dev: true 
